[package]
name = "warm-me-up"
version = "0.1.0"
authors = ["William Scullion <williamscullion@gmail.com>"]
edition = "2018"

[dependencies]
hex-literal = "0.2.1"
byteorder = "1.3.4"
structopt = "0.3.14"
lazy_static = "1.4.0"
regex = "1.3.7"
anyhow = "1.0.28"
