[package]
name = "warm-me-up"
version = "0.1.0"
authors = ["William Scullion <williamscullion@gmail.com>"]
edition = "2018"

[dependencies]
hex-literal = "0.2.0"
byteorder = "1.3.2"
structopt = "0.2.16"
lazy_static = "1.3.0"
regex = "1.1.7"
