[package]
name = "warmup"
version = "0.1.0"
authors = ["William Scullion <williamscullion@gmail.com>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.4"
byteorder = "1.3.1"
structopt = "0.2.15"
lazy_static = "1.3.0"
regex = "1.1.6"
